volumes:
    common_volume:

services:
    webservice:
        build: ./ws
        volumes:
            - common_volume:/output

    android:
        build:
            context: ./area
            dockerfile: Dockerfile.apk
        volumes:
            - common_volume:/output

    server:
        build: ./api
        ports:
            - 8080:8080
        volumes:
            - common_volume:/usr/src/app/src/output

    client_web:
        build: ./area
        depends_on:
            server:
                condition: service_started
        ports:
            - 8081:4200
        volumes:
            - common_volume:/usr/src/app/src/assets/output
