volumes:
    common_volume:
    log_volume:

services:
    server_service:
        build: ./ws
        volumes:
            - common_volume:/output
            - log_volume:/usr/src/app/logs

    client_mobile:
        build:
            context: ./area
            dockerfile: Dockerfile.apk
        volumes:
            - common_volume:/output

    server:
        build: ./api
        ports:
            - 8080:8080
        volumes:
            - common_volume:/usr/server/src/app/src/output
            - log_volume:/usr/server/src/ws/logs

    client_web:
        build: ./area
        depends_on:
            server:
                condition: service_started
            client_mobile:
                condition: service_completed_successfully
        ports:
            - 8081:8081
        volumes:
            - common_volume:/usr/src/app/src/assets/output
