name: AREA Development

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  test_docker_compose:
    name: Docker compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
  web_compile_test:
    name: Website (Angular)
    runs-on: ubuntu-latest
    needs: test_docker_compose
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install ionic and angular
        run: |
          npm i -g @ionic/cli
          npm i -g @angular/cli
      - name: Install npm dependencies
        run: |
          cd area
          npm i
      - name: Build website
        run: |
          cd area/
          npm run build
  android_compile_test:
    name: Mobile (Android)
    runs-on: ubuntu-latest
    needs: test_docker_compose
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Install ionic and angular
        run: |
          npm i -g @ionic/cli
          npm i -g @angular/cli
      - name: Install npm dependencies
        run: |
          cd area
          npm i
      - name: Export app on android
        run: |
          cd area/
          ionic capacitor build android
      - name: Grant execute permission for gradlew
        run: |
          cd area/android/
          chmod +x gradlew
      - name: Build with Gradle
        run: |
          cd area/android/
          ./gradlew assembleDebug
  ios_compile_test:
    name: Mobile (IOS)
    runs-on: macos-latest
    needs: test_docker_compose
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install ionic and angular
        run: |
          npm i -g @ionic/cli
          npm i -g @angular/cli
      - name: Install npm dependencies
        run: |
          cd area
          npm i
      - name: Export app on ios
        run: |
          cd area/
          ionic capacitor build ios
      - name: Xcode build
        run: |
          cd area/ios/App
          xcodebuild clean build -workspace 'App.xcworkspace' -scheme 'App' -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' -allowProvisioningUpdates DEVELOPMENT_TEAM=${{ secrets.SIGNING_TEAM_ID }}
  run_test:
    name: Angular (test)
    runs-on: ubuntu-latest
    needs:
      - web_compile_test
      - ios_compile_test
      - android_compile_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install ionic and angular
        run: |
          npm i -g @ionic/cli
          npm i -g @angular/cli
      - name: Install npm dependencies
        run: |
          cd area
          npm i
      - name: Launch test
        run: |
          cd area/
          npm run test
  open_pr:
    name: Create pull request
    runs-on: ubuntu-latest
    needs: run_test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'MERGE: dev to master'
          base: master
          branch: dev