name: Docker - testing docker compose

on:
  push:
    branches:
      - dev
      - master

jobs:
  test_docker_compose:
    name: Docker compose
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"