name: Build - Web

on:
  push:
    pull_request:
      branches-ignore:
        - 'ga-ignore-*'


jobs:
  web_compile_test:
    name: Website (Angular)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install ionic and angular
        run: |
          npm i -g @ionic/cli
          npm i -g @angular/cli
      - name: Install npm dependencies
        run: |
          cd area
          npm i
      - name: Build website
        run: |
          cd area/
          npm run build
  api_compile_test:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm dependencies
        run: |
          cd api
          npm i
      - name: Build website
        run: |
          cd api/
          npm run build