name: WebService - Pipeline

on:
  push:
    pull_request:
      branches-ignore:
        - 'ga-ignore-*'


jobs:
  ws_compile_test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm dependencies
        run: |
          cd ws
          npm i
      - name: Build WebService
        run: |
          cd ws/
          npm run build