name: Android - Pipeline

on:
  push:
    branches:
      - master

jobs:
  android_compile_test:
    name: Mobile (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Install ionic and angular
        run: |
          npm i -g @ionic/cli
          npm i -g @angular/cli
      - name: Install npm dependencies
        run: |
          cd area
          npm i
      - name: Export app on android
        run: |
          cd area/
          ionic capacitor build android
      - name: Grant execute permission for gradlew
        run: |
          cd area/android/
          chmod +x gradlew
      - name: Build with Gradle
        run: |
          cd area/android/
          ./gradlew assembleDebug