name: AREA Development

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  test_docker_compose:
    name: Docker compose (test)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compile and run docker compose
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./docker-compose.yml"
  ios_compile_test:
    name: Mobile (IOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm dependencies
        run: |
          cd area
          npm i
          ionic capacitor build ios
      - name: Build app
        run: xcodebuild clean build -project 'area.xcodeproj' -scheme 'area' -destination 'platform=iOS Simulator,name=iPhone 16 Pro,OS=latest'