name: API - Pipeline

on:
  push:
    pull_request:
      branches-ignore:
        - 'ga-ignore-*'


jobs:
  api_compile_test:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm dependencies
        run: |
          cd api
          npm i
      - name: Build website
        run: |
          cd api/
          npm run build