name: Build - all services

on:
  push:
    branches:
      - dev

jobs:
  web_compile_test:
    name: Website (Angular)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install ionic and angular
        run: |
          npm i -g @ionic/cli
          npm i -g @angular/cli
      - name: Install npm dependencies
        run: |
          cd area
          npm i
      - name: Build website
        run: |
          cd area/
          npm run build
  android_compile_test:
    name: Mobile (Android)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
      - name: Install ionic and angular
        run: |
          npm i -g @ionic/cli
          npm i -g @angular/cli
      - name: Install npm dependencies
        run: |
          cd area
          npm i
      - name: Export app on android
        run: |
          cd area/
          ionic capacitor build android
      - name: Grant execute permission for gradlew
        run: |
          cd area/android/
          chmod +x gradlew
      - name: Build with Gradle
        run: |
          cd area/android/
          ./gradlew assembleDebug
  ios_compile_test:
    name: Mobile (IOS)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install ionic and angular
        run: |
          npm i -g @ionic/cli
          npm i -g @angular/cli
      - name: Install npm dependencies
        run: |
          cd area
          npm i
      - name: Export app on ios
        run: |
          cd area/
          ionic capacitor build ios
      - name: Xcode build
        run: |
          cd area/ios/App
          xcodebuild clean build -workspace 'App.xcworkspace' -scheme 'App' -destination 'platform=iOS Simulator,name=iPhone 15 Pro,OS=latest' -allowProvisioningUpdates DEVELOPMENT_TEAM=${{ secrets.SIGNING_TEAM_ID }}
  api_compile_test:
    name: API
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm dependencies
        run: |
          cd api
          npm i
      - name: Build website
        run: |
          cd api/
          npm run build