name: Web - Pipeline

on:
  push:
    pull_request:
      branches-ignore:
        - 'ga-ignore-*'

jobs:
  web_compile_test:
    name: Build Website (Angular)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install ionic and angular
        run: |
          npm i -g @ionic/cli
          npm i -g @angular/cli
      - name: Install npm dependencies
        run: |
          cd area
          npm i
      - name: Build website
        run: |
          cd area/
          npm run build
