name: Coverage - all services

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'

jobs:
  api_coverage_test:
    name: API testing
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm dependencies
        run: |
          cd api
          npm i
      - name: Setup env file
        run: |
          cd api/
          echo "${{secrets.ENV_FILE}}" > .env
      - name: Run test
        run: |
          cd api/
          npm test
      - name: Summary Coverage Report
        uses: kcjpop/coverage-comments@v2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          coverage-file: 'api/coverage/lcov.info'